# Generated by Django 4.1 on 2022-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
