# Generated by Django 4.1 on 2022-11-15 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
