# Generated by Django 4.1 on 2022-11-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="uuid",
        ),
    ]
